theme: minima
title: GAME GEEK
author: Abhishek OJha
email: aojha6159@gmail.com
description: > 
 Here we give all info you need about new games and provide the associated links 

# social links
twitter_username: The Sarcastic Bihari 
github_username:  Abhishek123-code
show_excerpts: true # set to false to remove excerpts on the homepage
